# -*- coding: utf-8 -*-
"""wordcloud-generator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/############
"""

!pip install wordcloud

from os import path
import matplotlib.pyplot as plt
from PIL import Image
import numpy as np
from wordcloud import WordCloud, STOPWORDS

def google_authenticate():
  from google.colab import auth
  auth.authenticate_user()
  
  from googleapiclient.discovery import build
  drive_service = build('drive','v3')
  
  return drive_service

drive_service = google_authenticate()

def read_file(file_id):
  file_id = file_id
  
  import io
  from googleapiclient.http import MediaIoBaseDownload
  
  request = drive_service.files().get_media(fileId = file_id)
  downloaded = io.BytesIO()
  downloader = MediaIoBaseDownload(downloaded, request)
  done = False
  
  while done is False:
    _, done = downloader.next_chunk()
    
  downloaded.seek(0)
  
  return downloaded

text_file = read_file('#######')

document = text_file.read()

print(document)

wordcloud = WordCloud().generate(str(document))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")

image_file = read_file('########')

alice_mask = np.array(Image.open(image_file))

stopwords = set(STOPWORDS)

stopwords.add('said')

wc = WordCloud(background_color="white", max_words=2000, mask=alice_mask, stopwords=stopwords)

wc.generate(str(document))

plt.figure(figsize=(8,6), dpi=120)
plt.imshow(wc, interpolation='bilinear')
plt.axis("off")
plt.show()